# Generated by Django 6.0.7 on 2026-07-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=180)),
                ('pickup_location', models.CharField(max_length=180)),
                ('dropoff_location', models.CharField(max_length=180)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_miles', models.DecimalField(decimal_places=1, max_digits=8)),
                ('estimated_drive_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_elapsed_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('days_required', models.PositiveSmallIntegerField()),
                ('fuel_stops', models.PositiveSmallIntegerField()),
                ('rest_stops', models.PositiveSmallIntegerField()),
                ('plan_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
